# Generated by Django 3.2.8 on 2021-11-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='browseMovie',
            fields=[
                ('bid', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('bmovie_name', models.CharField(max_length=50)),
                ('bmovie_year', models.IntegerField(default=0)),
                ('bmovie_img', models.ImageField(upload_to='images/bimg')),
                ('bbody_img', models.ImageField(upload_to='images/bimg')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_year', models.IntegerField(default=0)),
                ('movie_img', models.ImageField(upload_to='images')),
                ('body_img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
