# Generated by Django 3.2.8 on 2021-11-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skipimovie', '0008_alter_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default='', max_length=20),
        ),
    ]
